version: "3.8"

services:
  spark:
    container_name: Spark_Master
    image: bitnami/spark:3.5.0
    build:
      context: .
      dockerfile: spark/Dockerfile.spark
    hostname: spark
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark
      SPARK_MASTER_PORT: "7077"
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - MIG_NET
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: bash -c "/opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    volumes:
      - ./spark-scripts:/spark-scripts
      - ./spark-logs:/opt/spark/logs

  spark-worker:
    container_name: Spark_Worker
    image: bitnami/spark:3.5.0
    build:
      context: .
      dockerfile: spark/Dockerfile.spark
    depends_on:
      spark:
        condition: service_healthy
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: "spark://spark:7077"
      SPARK_WORKER_CORES: "4"
      SPARK_WORKER_MEMORY: "4g"
    networks:
      - MIG_NET
    volumes:
      - ./spark-scripts:/spark-scripts
      - ./spark-logs:/opt/spark/logs

networks:
  MIG_NET:
    driver: bridge
